<?php

/**
 * @file
 * PowerBi connection settings.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_oauth2_client_edit_form_alter().
 *
 * Add tenant field to Power Bi service principal auth workflow configuration.
 */
function pwbi_form_oauth2_client_edit_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  if ($form_id === 'oauth2_client_edit_form' && $form['id']['#default_value'] === 'pwbi_service_principal') {
    /** @var \Drupal\pwbi\Oauth2Form\FormChanges $oauth_form_changes */
    $oauth_form_changes = \Drupal::service('pwbi.oauth_form_changes');
    $oauth_form_changes->addFormChanges($form, $form_state);
  }
}

/**
 * Implements hook_library_info_alter().
 */
function pwbi_library_info_alter(array &$libraries, string $module): void {
  if ('pwbi' !== $module) {
    return;
  }
  $path = _pwbi_get_path();
  if (isset($libraries['pwbi_client']) && $path) {
    $minified = file_exists($path . '/powerbi.min.js');
    $js_path = '/' . $path;
    $js = $minified ? $js_path . '/powerbi.min.js' : $js_path . '/powerbi.js';
    $libraries['pwbi_client']['js'] = [
      $js => [
        'minified' => $minified,
        'attributes' => ['defer' => TRUE],
      ],
    ];
  }
}

/**
 * Get powerbi-client path.
 *
 * @return string|null
 *   The path to the library.
 */
function _pwbi_get_path(): ?string {
  // The default way of installing the PowerBi client is through npm in the
  // module directory. Search primarily for the node_modules directory within
  // the module.
  $module_handler = \Drupal::getContainer()->get('module_handler');
  $module_path = $module_handler->getModule('pwbi')->getPath();
  if (file_exists($module_path . '/node_modules/powerbi-client/dist/powerbi.js')) {
    return $module_path . '/node_modules/powerbi-client/dist';
  }
  // If the library was not installed by the recommended way, look for other
  // places where the library can be found.
  if (function_exists('libraries_get_path') && $libraries_path = libraries_get_path('pwbi')) {
    return $libraries_path;
  }
  return NULL;
}
