# Schema for the power bi disclaimer banner configuration.

pwbi_banner.settings:
  type: config_object
  label: Power Bi disclaimer banner
  mapping:
    banner_type:
      type: integer
      label: Banner type
    display_options:
      type: integer
      label: Display options
    banner_text:
      type: mapping
      label: Banner text
      mapping:
        value:
          type: string
        format:
          type: string
