pwbi_purge.settings:
  type: config_object
  label: 'Power BI purge settings'
  mapping:
    cron_window:
      type: integer
      label: 'Time between cron runs in seconds or slightly more'
      constraints:
        Range:
          min: 1
          max: 3600
