<?php

/**
 * @file
 * Install, update and uninstall for the Power BI API Request Mock Test.
 */

declare(strict_types=1);

/**
 * Implements hook_uninstall().
 */
function pwbi_api_request_mock_test_uninstall(): void {
  $config_list = [
    'media.type.pwbi_media_report',
    'core.entity_form_display.media.power_bi_report.default',
    'core.entity_view_display.media.power_bi_report.default',
    'field.field.media.power_bi_report.field_media_pwbi_embed_visual',
    'field.storage.media.field_media_pwbi_embed_visual',
  ];
  foreach ($config_list as $config_name) {
    Drupal::configFactory()->getEditable($config_name)->delete();
  }
}
