<?php

/**
 * @file
 * PowerBi banner module.
 */

declare(strict_types=1);

/**
 * Implements hook_library_info_alter().
 */
function pwbi_banner_library_info_alter(array &$libraries, string $module): void {
  if (
    "core" === $module &&
    isset($libraries['components.pwbi--pwbi-embed']) &&
    isset($libraries['components.pwbi_banner--disclaimer-banner'])
  ) {
    $libraries['components.pwbi--pwbi-embed']['dependencies'][] = 'core/components.pwbi_banner--disclaimer-banner';
  }
}
